name: real time company deployment
on: [ push ]
jobs:
  test-staging:
   name: Test and Deploy to Staging
   strategy:
    matrix:
      os: [ubuntu-latest, windows-latest]
      node-version: [22, 20]
   env:
     NODE_ENV: ${{ matrix.node-version }}
     VIRTUAL_ENV: ${{ matrix.os }}
 
   runs-on: ${{ env.VIRTUAL_ENV }}
   environment: practice

   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_ENV }}

    - name: Install dependencies
      run: npm install

    - name: lint code
      run: npm run lint

    - name: Run tests
      run: npm test
  
  deployment:
    name: Deploy to dokcerhub
    runs-on: ubuntu-latest
    needs: test-staging
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/production:latest
            ${{ vars.DOCKER_USERNAME }}/production:${{ github.sha }}

